Clarify missing `use` paramerter
spiffe/spiffe pull request #122
Opened 2020-04-30 21:03 UTC by spikecurtis

Fixes #121

2020-05-13 23:58 UTC, justinburke requested changes
One minor request below, otherwise LGTM.

2020-05-13 23:58 UTC, justinburke commented on standards/SPIFFE_Trust_Domain_and_Bundle.md
> +The `use` parameter MUST be set. Its value indicates the type of identity document (or SVID) that it is authoritative for. At the time of this writing, only two SVID types are supported: `x509-svid`
s/or unknown/or an unknown/

2020-05-14 18:27 UTC, azdagron reviewed
Also LGTM, pending Justin's suggestion.

2020-05-14 20:35 UTC, spikecurtis commented
@azdagron @justinburke fixed.

2020-05-27 00:58 UTC, justinburke approved these changes

2020-05-28 20:07 UTC, merged