Adding note on how to handle casing of SPIFFE IDs
spiffe/spiffe pull request #130
Opened 2020-06-25 23:27 UTC by mweissbacher

Signed-off-by: Michael Weissbacher <mweissbacher@squareup.com>

2020-06-26 19:41 UTC, spikecurtis requested changes
small nit, otherwise sounds good to me

2020-06-26 19:41 UTC, spikecurtis commented on standards/SPIFFE-ID.md
> +SPIFFE IDs follow the URI specification as defined by [RFC 3986](https://tools.ietf.org/html/rfc3986). The schema and trust domain name of the SPIFFE ID is case-insensitive. The path is case-sensitiv
```suggestion
SPIFFE IDs follow the URI specification as defined by [RFC 3986](https://tools.ietf.org/html/rfc3986). The scheme and trust domain name of the SPIFFE ID are case-insensitive. The path is case-sensitive.
```

2020-06-26 22:50 UTC, spikecurtis approved these changes

2020-06-27 00:42 UTC, justinburke approved these changes

2020-06-27 00:51 UTC, justinburke commented
BTW, thanks for taking the time to put together this PR.

2020-06-29 15:43 UTC, merged