Provide extra details on claims processing
spiffe/spiffe pull request #184
Opened 2021-05-27 17:12 UTC by azdagron

This PR addresses a recent ambiguity brought up in #182 (thanks, @rturner3!). It attempts to add clarifying language that the implementation must process the claims and return them to the client, but may selectively prune that list.

2021-05-27 22:39 UTC, spikecurtis requested changes

2021-05-27 22:39 UTC, spikecurtis commented on standards/SPIFFE_Workload_API.md
>      // JWT-SVID.
```suggestion
    // Required. Claims contained within the payload of the validated JWT-SVID.
    // This includes both SPIFFE-required and non-required claims.
```

2021-05-27 22:56 UTC, azdagron commented on standards/SPIFFE_Workload_API.md
>      // JWT-SVID.
:+1:

2021-06-03 18:10 UTC, evan2645 submitted a review, later dismissed

2021-06-03 20:20 UTC, justinburke commented on standards/SPIFFE_Workload_API.md
> +The `ValidateJWTSVID` RPC validates JWT-SVIDs for a specific audience on behalf of a client. Further, the server MUST parse and validate the JWT-SVID according to the rules outlined in the [JWT-SVID]
```suggestion
The `ValidateJWTSVID` RPC validates JWT-SVIDs for a specific audience on behalf of a client. Further, the server MUST parse and validate the JWT-SVID according to the rules outlined in the [JWT-SVID](JWT-SVID.md) specification. The claims embedded in the JWT-SVID payload SHOULD be provided in the `claims` field in the `ValidateJWTSVIDResponse`; the claims defined by this specification above are required, however implementations MAY filter non-SPIFFE claims before returning them to the client. SPIFFE claims are required for interoperability.
```

2021-06-17 23:19 UTC, spikecurtis reviewed
LGTM with Justin's suggested wording change.

2021-07-01 19:54 UTC, azdagron commented
Awesome. I've made Justin's suggested edits.

2021-07-01 20:23 UTC, evan2645 approved these changes

2021-07-01 20:25 UTC, spikecurtis approved these changes

2021-07-01 20:25 UTC, merged