Update README.md
spiffe/spiffe pull request #54
Opened 2018-01-17 23:19 UTC by suniljames

SCYTALE TEAM: IGNORE THIS

Small change for you guys to consider.

2018-01-17 23:19 UTC, suniljames commented on README.md
> +Hello World ... The Secure Production Identity Framework For Everyone (SPIFFE) Project defines a framework and set of
THIS IS A TERRIBLE IDEA

2018-01-18 18:13 UTC, ajessup requested changes
Nope.

2018-01-18 18:14 UTC, closed without merging

2018-09-18 13:27 UTC, sejal1s commented
Hi Sunil,

I am trying to open the link for Spire design document/ref architecture. But I guess link does not exist anymore. Can you please help with new path.

Path mentioned was: https://github.com/spiffe/community/blob/master/contributors/design%20docs/readme.md

Thanks.

2018-09-18 13:28 UTC, sejal1s commented
I wish to try to setup the spire environment on Kubernetes with bare metal VMs.
Your guidance or any pointer/URL would be appreciated.

2018-09-18 16:00 UTC, ajessup commented
Hi @sejal1s - this issue is closed and no longer monitored. For the broken link, could you file a new issue under the SPIFFE project as described [here](https://help.github.com/articles/creating-an-issue/)?

As for help on Kubernetes, we're working on better documentation for this. In the meantime, the best place to get help is in the #help channel of our Slack workspace, which is at https://spiffe.slack.com/ (you can sign up at https://slack.spiffe.io/).